version: '3'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - backend
    
  web:
    image: marketingharp/flaskapp
    ports:
      - '5000:80'
    networks:
      - backend

  prometheus:
    image: prometheus
    ports:
      - 9090:9090 # default port is 9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./alert.rules:/prometheus/alert.rules

  alertmanager:
    image: prometheus/alertmanager
    ports:
      - 9093:9093 # default alertmanager is 9093
  
# networks:
#   backend:
#     name: backend