apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: | 
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'web'
        static_configs:
          - targets: ['web:80']

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - 'alertmanager:9093'  # 9093 is default for alertmanager

    rule_files:
      - '/etc/prometheus/rules.yml'

