apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.service: mongo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        io.network/backend: "true"
        io.service: mongo
    spec:
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-storage-pvc
      containers:
        - image: mongo
          volumeMounts:
          - mountPath: /data/db
            name: mongo-storage
          name: mongo
          ports:
            - containerPort: 27017
          resources: {}
      restartPolicy: Always
status: {}
