apiVersion: v1
kind: Service
metadata:
  labels:
    io.service: web
  name: web
spec:
  type: LoadBalancer
  selector:
    io.service: web  # Matches pods with specific labels
  ports:
  - protocol: TCP  # or UDP
    port: 5000  # Port exposed externally
    targetPort: 80  # Port the container listens on