apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.service: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        io.network/backend: "true"
        io.service: web
    spec:
      containers:
        - image: marketingharp/flaskapp:v2
          name: web
          ports:
            - containerPort: 80
          resources: {}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
status: {}
