global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'Flask'
    static_configs:
      - targets: ['web:80']

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'  # 9093 is default for alertmanager

      
rule_files:
  - '/prometheus/alert.rules'

