apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  config.yml: | 
    global:
      resolve_timeout: 5m
      slack_api_url: '{{ .Values.SLACK_WEBHOOK_URL }}'
    route:
      group_by: ['alertname', 'severity']
    receivers:
    - name: 'slack-notifications'
      slack_configs:
      - channel: '#assignment2slack-am-mj'
        send_resolved: true
